### ISSUE TITLE
你好啊

### ISSUE THREAD

**Issue by Block2B** [alpha87/QuantumultX-Profiles#1]
用神机YouTube去不掉广告，自己一个个添加的list，但是用你的就能去，你是加入了哪些东西呢

**Comment by alpha87** [comment]
`[rewrite_local]` 里有一些屏蔽 YouTube 广告相关的链接，拒绝即可，但如果是 YouTube premium，可能需要删除拒绝的内容。

**Comment by alpha87** [comment]
@Block2B [rewrite_local] 里有一些屏蔽 YouTube 广告相关的链接，拒绝即可，但如果是 YouTube premium，可能需要删除拒绝的内容。
